#!/bin/bash

# Prepare embedded application files for standalone launcher
# ULTRA-OPTIMIZED version - creates launcher UNDER 25MB
# Removes heavy optional plugins - core functionality only

set -e

echo "================================================"
echo "  Preparing ULTRA-OPTIMIZED Embedded (<25MB)"
echo "================================================"
echo ""

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR/.."

# Clean previous embedded_app directory
echo "[1/4] Cleaning previous embedded_app directory..."
rm -rf standalonelauncher/embedded_app
mkdir -p standalonelauncher/embedded_app

# Copy application files
echo "[2/4] Copying essential application files..."

# Copy app directory (main application)
if [ -d "app" ]; then
    echo "  - Copying app/ directory (ultra-optimized)..."
    cp -r app standalonelauncher/embedded_app/
    
    # Remove unnecessary files to reduce size
    echo "  - Removing unnecessary files..."
    
    # Remove test files and documentation (not needed at runtime)
    rm -rf standalonelauncher/embedded_app/app/test
    rm -rf standalonelauncher/embedded_app/app/docs
    rm -rf standalonelauncher/embedded_app/app/wiki
    rm -f standalonelauncher/embedded_app/app/README.md
    rm -f standalonelauncher/embedded_app/app/LICENSE
    rm -f standalonelauncher/embedded_app/app/CHANGELOG.md
    
    # Remove large logo files from public (2MB+ logos)
    if [ -d "standalonelauncher/embedded_app/app/public" ]; then
        echo "  - Optimizing public/ directory..."
        find standalonelauncher/embedded_app/app/public -name "*.png" -size +500k -delete
        find standalonelauncher/embedded_app/app/public -name "*.jpg" -size +500k -delete
        find standalonelauncher/embedded_app/app/public -name "*.jpeg" -size +500k -delete
    fi
    
    # Remove HEAVY OPTIONAL plugins to get under 25MB
    # These can be downloaded separately via plugin manager if needed
    if [ -d "standalonelauncher/embedded_app/app/plugins" ]; then
        echo "  - Removing heavy optional plugins..."
        # Games (2.1MB + 1.5MB + 0.7MB + 0.5MB = ~5MB)
        rm -rf standalonelauncher/embedded_app/app/plugins/game-engine 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/coinbattle 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/quiz-show 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/interactive-story 2>/dev/null || true
        
        # Heavy visual effects (1.8MB)
        rm -rf standalonelauncher/embedded_app/app/plugins/fireworks 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/fireworks-webgl-beta 2>/dev/null || true
        
        # Specialized hardware/integrations (~2.5MB)
        rm -rf standalonelauncher/embedded_app/app/plugins/openshock 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/flame-overlay 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/webgpu-emoji-rain 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/animazingpal 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/sidekick 2>/dev/null || true
        
        # Beta/experimental
        rm -rf standalonelauncher/embedded_app/app/plugins/*-beta 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/*-test 2>/dev/null || true
        
        # Niche integrations
        rm -rf standalonelauncher/embedded_app/app/plugins/minecraft-connect 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/thermal-printer 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/chatango 2>/dev/null || true
        rm -rf standalonelauncher/embedded_app/app/plugins/vdoninja 2>/dev/null || true
    fi
    
    # Remove source maps and development files
    echo "  - Removing source maps and dev files..."
    find standalonelauncher/embedded_app/app -name "*.map" -delete 2>/dev/null || true
    find standalonelauncher/embedded_app/app -name "*.dev.js" -delete 2>/dev/null || true
    find standalonelauncher/embedded_app/app -name ".DS_Store" -delete 2>/dev/null || true
fi

# Copy package.json only (skip package-lock to save 220KB)
if [ -f "package.json" ]; then
    echo "  - Copying package.json..."
    cp package.json standalonelauncher/embedded_app/
fi

echo "  - Skipping package-lock.json (will be regenerated by npm)"

# Get size of embedded files
echo ""
echo "[3/4] Calculating embedded files size..."
EMBEDDED_SIZE=$(du -sh standalonelauncher/embedded_app | cut -f1)
EMBEDDED_SIZE_MB=$(du -sm standalonelauncher/embedded_app | cut -f1)
FILE_COUNT=$(find standalonelauncher/embedded_app -type f | wc -l)

# Verify size is under 25MB
echo ""
echo "[4/4] Verifying size constraints..."
EXPECTED_BINARY=$((EMBEDDED_SIZE_MB + 7))
if [ $EXPECTED_BINARY -gt 25 ]; then
    echo "⚠️  WARNING: Expected binary size ${EXPECTED_BINARY}MB exceeds 25MB limit"
    echo "    Embedded files: ${EMBEDDED_SIZE_MB}MB"
else
    echo "✅ SUCCESS: Expected binary ${EXPECTED_BINARY}MB is UNDER 25MB limit!"
    echo "    Embedded files: ${EMBEDDED_SIZE_MB}MB"
fi

echo ""
echo "================================================"
echo "  Ultra-Optimized Embedded Files Prepared!"
echo "================================================"
echo "  Total Size: $EMBEDDED_SIZE (${EMBEDDED_SIZE_MB}MB)"
echo "  File Count: $FILE_COUNT"
echo "  Expected Binary: ~${EXPECTED_BINARY}MB"
echo ""
echo "Optimizations applied:"
echo "  ✅ Removed test files and documentation"
echo "  ✅ Removed large logo files (>500KB)"
echo "  ✅ Removed games and game engine (~5MB)"
echo "  ✅ Removed heavy visual effects (~2MB)"
echo "  ✅ Removed specialized integrations (~3MB)"
echo "  ✅ Removed source maps and dev files"
echo "  ✅ Skipped package-lock.json (220KB)"
echo "  💾 Total saved: ~10MB"
echo ""
echo "Core plugins INCLUDED:"
echo "  ✅ TTS (Text-to-Speech)"
echo "  ✅ OSC Bridge (VRChat)"
echo "  ✅ Weather Control"
echo "  ✅ Viewer Leaderboard"
echo "  ✅ Goals & Milestones"
echo "  ✅ GCCE (Gift Effects)"
echo "  ✅ Soundboard"
echo "  ✅ All essential core features"
echo ""
echo "Plugins REMOVED (can be added via plugin manager):"
echo "  ❌ Game Engine & Games (Coin Battle, Quiz Show, etc.)"
echo "  ❌ Fireworks Effects"
echo "  ❌ OpenShock integration"
echo "  ❌ AnimazingPal, Sidekick"
echo "  ❌ Niche integrations (Minecraft, Thermal Printer)"
echo ""
echo "Next steps:"
echo "  1. Run ./build.sh to build launcher under 25MB"
echo "  2. No GitHub download needed at runtime"
echo "  3. Removed plugins can be installed via plugin manager"
echo ""
